apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ .Chart.Name }}-success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: pod-ready-rate
      initialDelay: 45s
      interval: 15s
      count: 3
      successCondition: result[0] >= 0.5
      failureLimit: 2
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            (sum(kube_pod_status_ready{namespace="itsm", condition="true", pod=~"{{`{{args.service-name}}`}}-.*"}) or vector(0))
            /
            (count(kube_pod_status_ready{namespace="itsm", condition="true", pod=~"{{`{{args.service-name}}`}}-.*"} or kube_pod_status_ready{namespace="itsm", condition="false", pod=~"{{`{{args.service-name}}`}}-.*"}) or vector(1))
