---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jwt-secret
  namespace: itsm
spec:
  encryptedData:
    JWT_SECRET: AgAhcviOqPuE395bYKDSZWnZa1Kc8VYKK0UCEBHVBnCP/rtKBwXyBSNMThECHcfOQfEo3Az+Nex/UjwlN3umSwY5NwIj/9gX6c9RLV/4BTXrD5ORONUcNnfoQICqe5A9wQX6x0eY+6dOtbVo8hdlwtz4diW7/+RN5mM+XuiOZ8WgLZFx/+J5756PPoSkuTzUu3vPbyj4SPrwJfk2Tj3sMEn/uSCO8pK04gY6ZUm/iHDcb6Ufy8euDlqY173wqjEk+xPB/GBmdnQ6iazZTyUhy7QA8VfHSLfL0A1XNPf+d3hYV16VSBJSEU1RDVkAp9MmCBQD+uUOjheYPA1kdbM7JkNW62KgfrW0NKuq6+fS65NFUl1poVFpXbvpoexsUgEQtBbuJbM6JsafUWhLL7VcwweCsE76KEhxe5k6z7D7ZieEQhzue6fPBDIB8uom224iGzLALE+l0U68NokEXgBtrdd1HEPQ5xsyocdCeH8/NRQ1D4Jv/qQiDfhrAVZUOK+VUVAILvA6nirGrtAK2eyA2s0t+DL5LDw7oDaeVDHF14Q9/IZQrzEGT9VL9q1UL+Q3Mt2HFH+9JuYR5RDMU3ThltcEJvmIDO5BVDMObErMEaQpQoIQXEnH9wsTrHct8czDRzBzNuWs/l4gj6cyIOdqMDgeo7WvqSqjyCL2q9xYmjCLi8FdWrtegJzCKs7PR++ctWMsaiLU9zXmtLQ4rZD1lbjXskfxU103HQkuVhWJf7ODLr3DxM1bNc9o8rfpK97Mc+98BOo=
  template:
    metadata:
      creationTimestamp: null
      name: jwt-secret
      namespace: itsm
